/* Generated by hyperv_wmi_generator.py */



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Msvm_ComputerSystem
 */

#define MSVM_COMPUTERSYSTEM_RESOURCE_URI \
    "http://schemas.microsoft.com/wbem/wsman/1/wmi/root/virtualization/Msvm_ComputerSystem"

#define MSVM_COMPUTERSYSTEM_CLASSNAME \
    "Msvm_ComputerSystem"

#define MSVM_COMPUTERSYSTEM_WQL_SELECT \
    "select * from Msvm_ComputerSystem "

struct _Msvm_ComputerSystem_Data {
    XML_TYPE_STR Caption;
    XML_TYPE_STR Description;
    XML_TYPE_STR ElementName;
    XML_TYPE_STR InstallDate;
    XML_TYPE_DYN_ARRAY OperationalStatus;
    XML_TYPE_DYN_ARRAY StatusDescriptions;
    XML_TYPE_STR Status;
    XML_TYPE_UINT16 HealthState;
    XML_TYPE_UINT16 EnabledState;
    XML_TYPE_STR OtherEnabledState;
    XML_TYPE_UINT16 RequestedState;
    XML_TYPE_UINT16 EnabledDefault;
    XML_TYPE_STR TimeOfLastStateChange;
    XML_TYPE_STR CreationClassName;
    XML_TYPE_STR Name;
    XML_TYPE_STR PrimaryOwnerName;
    XML_TYPE_STR PrimaryOwnerContact;
    XML_TYPE_DYN_ARRAY Roles;
    XML_TYPE_STR NameFormat;
    XML_TYPE_DYN_ARRAY OtherIdentifyingInfo;
    XML_TYPE_DYN_ARRAY IdentifyingDescriptions;
    XML_TYPE_DYN_ARRAY Dedicated;
    XML_TYPE_DYN_ARRAY OtherDedicatedDescriptions;
    XML_TYPE_UINT16 ResetCapability;
    XML_TYPE_DYN_ARRAY PowerManagementCapabilities;
    XML_TYPE_UINT64 OnTimeInMilliseconds;
    XML_TYPE_STR TimeOfLastConfigurationChange;
    XML_TYPE_UINT32 ProcessID;
    XML_TYPE_DYN_ARRAY AssignedNumaNodeList;
};

SER_DECLARE_TYPE(Msvm_ComputerSystem_Data);

struct _Msvm_ComputerSystem {
    XmlSerializerInfo *serializerInfo;
    Msvm_ComputerSystem_Data *data;
    Msvm_ComputerSystem *next;
};



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Msvm_ConcreteJob
 */

#define MSVM_CONCRETEJOB_RESOURCE_URI \
    "http://schemas.microsoft.com/wbem/wsman/1/wmi/root/virtualization/Msvm_ConcreteJob"

#define MSVM_CONCRETEJOB_CLASSNAME \
    "Msvm_ConcreteJob"

#define MSVM_CONCRETEJOB_WQL_SELECT \
    "select * from Msvm_ConcreteJob "

struct _Msvm_ConcreteJob_Data {
    XML_TYPE_STR Caption;
    XML_TYPE_STR Description;
    XML_TYPE_STR ElementName;
    XML_TYPE_STR InstallDate;
    XML_TYPE_DYN_ARRAY OperationalStatus;
    XML_TYPE_DYN_ARRAY StatusDescriptions;
    XML_TYPE_STR Status;
    XML_TYPE_UINT16 HealthState;
    XML_TYPE_STR JobStatus;
    XML_TYPE_STR TimeSubmitted;
    XML_TYPE_STR ScheduledStartTime;
    XML_TYPE_STR StartTime;
    XML_TYPE_STR ElapsedTime;
    XML_TYPE_UINT32 JobRunTimes;
    XML_TYPE_UINT8 RunMonth;
    XML_TYPE_INT8 RunDay;
    XML_TYPE_INT8 RunDayOfWeek;
    XML_TYPE_STR RunStartInterval;
    XML_TYPE_UINT16 LocalOrUtcTime;
    XML_TYPE_STR UntilTime;
    XML_TYPE_STR Notify;
    XML_TYPE_STR Owner;
    XML_TYPE_UINT32 Priority;
    XML_TYPE_UINT16 PercentComplete;
    XML_TYPE_BOOL DeleteOnCompletion;
    XML_TYPE_UINT16 ErrorCode;
    XML_TYPE_STR ErrorDescription;
    XML_TYPE_STR ErrorSummaryDescription;
    XML_TYPE_UINT16 RecoveryAction;
    XML_TYPE_STR OtherRecoveryAction;
    XML_TYPE_STR InstanceID;
    XML_TYPE_STR Name;
    XML_TYPE_UINT16 JobState;
    XML_TYPE_STR TimeOfLastStateChange;
    XML_TYPE_STR TimeBeforeRemoval;
    XML_TYPE_BOOL Cancellable;
};

SER_DECLARE_TYPE(Msvm_ConcreteJob_Data);

struct _Msvm_ConcreteJob {
    XmlSerializerInfo *serializerInfo;
    Msvm_ConcreteJob_Data *data;
    Msvm_ConcreteJob *next;
};



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Msvm_MemorySettingData
 */

#define MSVM_MEMORYSETTINGDATA_RESOURCE_URI \
    "http://schemas.microsoft.com/wbem/wsman/1/wmi/root/virtualization/Msvm_MemorySettingData"

#define MSVM_MEMORYSETTINGDATA_CLASSNAME \
    "Msvm_MemorySettingData"

#define MSVM_MEMORYSETTINGDATA_WQL_SELECT \
    "select * from Msvm_MemorySettingData "

struct _Msvm_MemorySettingData_Data {
    XML_TYPE_STR Caption;
    XML_TYPE_STR Description;
    XML_TYPE_STR InstanceID;
    XML_TYPE_STR ElementName;
    XML_TYPE_UINT16 ResourceType;
    XML_TYPE_STR OtherResourceType;
    XML_TYPE_STR ResourceSubType;
    XML_TYPE_STR PoolID;
    XML_TYPE_UINT16 ConsumerVisibility;
    XML_TYPE_DYN_ARRAY HostResource;
    XML_TYPE_STR AllocationUnits;
    XML_TYPE_UINT64 VirtualQuantity;
    XML_TYPE_UINT64 Reservation;
    XML_TYPE_UINT64 Limit;
    XML_TYPE_UINT32 Weight;
    XML_TYPE_BOOL AutomaticAllocation;
    XML_TYPE_BOOL AutomaticDeallocation;
    XML_TYPE_STR Parent;
    XML_TYPE_DYN_ARRAY Connection;
    XML_TYPE_STR Address;
    XML_TYPE_UINT16 MappingBehavior;
    XML_TYPE_BOOL IsVirtualized;
    XML_TYPE_STR DeviceID;
    XML_TYPE_STR DeviceIDFormat;
    XML_TYPE_BOOL DynamicMemoryEnabled;
};

SER_DECLARE_TYPE(Msvm_MemorySettingData_Data);

struct _Msvm_MemorySettingData {
    XmlSerializerInfo *serializerInfo;
    Msvm_MemorySettingData_Data *data;
    Msvm_MemorySettingData *next;
};



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Msvm_ProcessorSettingData
 */

#define MSVM_PROCESSORSETTINGDATA_RESOURCE_URI \
    "http://schemas.microsoft.com/wbem/wsman/1/wmi/root/virtualization/Msvm_ProcessorSettingData"

#define MSVM_PROCESSORSETTINGDATA_CLASSNAME \
    "Msvm_ProcessorSettingData"

#define MSVM_PROCESSORSETTINGDATA_WQL_SELECT \
    "select * from Msvm_ProcessorSettingData "

struct _Msvm_ProcessorSettingData_Data {
    XML_TYPE_STR Caption;
    XML_TYPE_STR Description;
    XML_TYPE_STR InstanceID;
    XML_TYPE_STR ElementName;
    XML_TYPE_UINT16 ResourceType;
    XML_TYPE_STR OtherResourceType;
    XML_TYPE_STR ResourceSubType;
    XML_TYPE_STR PoolID;
    XML_TYPE_UINT16 ConsumerVisibility;
    XML_TYPE_DYN_ARRAY HostResource;
    XML_TYPE_STR AllocationUnits;
    XML_TYPE_UINT64 VirtualQuantity;
    XML_TYPE_UINT64 Reservation;
    XML_TYPE_UINT64 Limit;
    XML_TYPE_UINT32 Weight;
    XML_TYPE_BOOL AutomaticAllocation;
    XML_TYPE_BOOL AutomaticDeallocation;
    XML_TYPE_STR Parent;
    XML_TYPE_DYN_ARRAY Connection;
    XML_TYPE_STR Address;
    XML_TYPE_UINT16 MappingBehavior;
    XML_TYPE_BOOL IsVirtualized;
    XML_TYPE_STR DeviceID;
    XML_TYPE_STR DeviceIDFormat;
    XML_TYPE_UINT16 ProcessorsPerSocket;
    XML_TYPE_UINT16 SocketCount;
    XML_TYPE_BOOL ThreadsEnabled;
    XML_TYPE_BOOL LimitCPUID;
    XML_TYPE_BOOL LimitProcessorFeatures;
};

SER_DECLARE_TYPE(Msvm_ProcessorSettingData_Data);

struct _Msvm_ProcessorSettingData {
    XmlSerializerInfo *serializerInfo;
    Msvm_ProcessorSettingData_Data *data;
    Msvm_ProcessorSettingData *next;
};



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Msvm_VirtualSystemSettingData
 */

#define MSVM_VIRTUALSYSTEMSETTINGDATA_RESOURCE_URI \
    "http://schemas.microsoft.com/wbem/wsman/1/wmi/root/virtualization/Msvm_VirtualSystemSettingData"

#define MSVM_VIRTUALSYSTEMSETTINGDATA_CLASSNAME \
    "Msvm_VirtualSystemSettingData"

#define MSVM_VIRTUALSYSTEMSETTINGDATA_WQL_SELECT \
    "select * from Msvm_VirtualSystemSettingData "

struct _Msvm_VirtualSystemSettingData_Data {
    XML_TYPE_STR Caption;
    XML_TYPE_STR Description;
    XML_TYPE_STR ElementName;
    XML_TYPE_STR InstanceID;
    XML_TYPE_STR SystemName;
    XML_TYPE_UINT16 SettingType;
    XML_TYPE_UINT16 VirtualSystemType;
    XML_TYPE_STR OtherVirtualSystemType;
    XML_TYPE_BOOL AutoActivate;
    XML_TYPE_STR CreationTime;
    XML_TYPE_STR Notes;
    XML_TYPE_STR BIOSGUID;
    XML_TYPE_STR BIOSSerialNumber;
    XML_TYPE_STR BaseBoardSerialNumber;
    XML_TYPE_STR ChassisSerialNumber;
    XML_TYPE_STR ChassisAssetTag;
    XML_TYPE_BOOL BIOSNumLock;
    XML_TYPE_DYN_ARRAY BootOrder;
    XML_TYPE_STR Parent;
    XML_TYPE_DYN_ARRAY NumaNodeList;
    XML_TYPE_BOOL NumaNodesAreRequired;
};

SER_DECLARE_TYPE(Msvm_VirtualSystemSettingData_Data);

struct _Msvm_VirtualSystemSettingData {
    XmlSerializerInfo *serializerInfo;
    Msvm_VirtualSystemSettingData_Data *data;
    Msvm_VirtualSystemSettingData *next;
};



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Win32_ComputerSystem
 */

#define WIN32_COMPUTERSYSTEM_RESOURCE_URI \
    "http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_ComputerSystem"

#define WIN32_COMPUTERSYSTEM_CLASSNAME \
    "Win32_ComputerSystem"

#define WIN32_COMPUTERSYSTEM_WQL_SELECT \
    "select * from Win32_ComputerSystem "

struct _Win32_ComputerSystem_Data {
    XML_TYPE_UINT16 AdminPasswordStatus;
    XML_TYPE_BOOL AutomaticManagedPagefile;
    XML_TYPE_BOOL AutomaticResetBootOption;
    XML_TYPE_BOOL AutomaticResetCapability;
    XML_TYPE_UINT16 BootOptionOnLimit;
    XML_TYPE_UINT16 BootOptionOnWatchDog;
    XML_TYPE_BOOL BootROMSupported;
    XML_TYPE_STR BootupState;
    XML_TYPE_STR Caption;
    XML_TYPE_UINT16 ChassisBootupState;
    XML_TYPE_STR CreationClassName;
    XML_TYPE_INT16 CurrentTimeZone;
    XML_TYPE_BOOL DaylightInEffect;
    XML_TYPE_STR Description;
    XML_TYPE_STR DNSHostName;
    XML_TYPE_STR Domain;
    XML_TYPE_UINT16 DomainRole;
    XML_TYPE_BOOL EnableDaylightSavingsTime;
    XML_TYPE_UINT16 FrontPanelResetStatus;
    XML_TYPE_BOOL InfraredSupported;
    XML_TYPE_STR InstallDate;
    XML_TYPE_UINT16 KeyboardPasswordStatus;
    XML_TYPE_STR LastLoadInfo;
    XML_TYPE_STR Manufacturer;
    XML_TYPE_STR Model;
    XML_TYPE_STR Name;
    XML_TYPE_STR NameFormat;
    XML_TYPE_BOOL NetworkServerModeEnabled;
    XML_TYPE_UINT32 NumberOfLogicalProcessors;
    XML_TYPE_UINT32 NumberOfProcessors;
    XML_TYPE_DYN_ARRAY OEMLogoBitmap;
    XML_TYPE_DYN_ARRAY OEMStringArray;
    XML_TYPE_BOOL PartOfDomain;
    XML_TYPE_INT64 PauseAfterReset;
    XML_TYPE_UINT16 PCSystemType;
    XML_TYPE_DYN_ARRAY PowerManagementCapabilities;
    XML_TYPE_BOOL PowerManagementSupported;
    XML_TYPE_UINT16 PowerOnPasswordStatus;
    XML_TYPE_UINT16 PowerState;
    XML_TYPE_UINT16 PowerSupplyState;
    XML_TYPE_STR PrimaryOwnerContact;
    XML_TYPE_STR PrimaryOwnerName;
    XML_TYPE_UINT16 ResetCapability;
    XML_TYPE_INT16 ResetCount;
    XML_TYPE_INT16 ResetLimit;
    XML_TYPE_DYN_ARRAY Roles;
    XML_TYPE_STR Status;
    XML_TYPE_DYN_ARRAY SupportContactDescription;
    XML_TYPE_UINT16 SystemStartupDelay;
    XML_TYPE_DYN_ARRAY SystemStartupOptions;
    XML_TYPE_UINT8 SystemStartupSetting;
    XML_TYPE_STR SystemType;
    XML_TYPE_UINT16 ThermalState;
    XML_TYPE_UINT64 TotalPhysicalMemory;
    XML_TYPE_STR UserName;
    XML_TYPE_UINT16 WakeUpType;
    XML_TYPE_STR Workgroup;
};

SER_DECLARE_TYPE(Win32_ComputerSystem_Data);

struct _Win32_ComputerSystem {
    XmlSerializerInfo *serializerInfo;
    Win32_ComputerSystem_Data *data;
    Win32_ComputerSystem *next;
};



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Win32_Processor
 */

#define WIN32_PROCESSOR_RESOURCE_URI \
    "http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/Win32_Processor"

#define WIN32_PROCESSOR_CLASSNAME \
    "Win32_Processor"

#define WIN32_PROCESSOR_WQL_SELECT \
    "select * from Win32_Processor "

struct _Win32_Processor_Data {
    XML_TYPE_UINT16 AddressWidth;
    XML_TYPE_UINT16 Architecture;
    XML_TYPE_UINT16 Availability;
    XML_TYPE_STR Caption;
    XML_TYPE_UINT32 ConfigManagerErrorCode;
    XML_TYPE_BOOL ConfigManagerUserConfig;
    XML_TYPE_UINT16 CpuStatus;
    XML_TYPE_STR CreationClassName;
    XML_TYPE_UINT32 CurrentClockSpeed;
    XML_TYPE_UINT16 CurrentVoltage;
    XML_TYPE_UINT16 DataWidth;
    XML_TYPE_STR Description;
    XML_TYPE_STR DeviceID;
    XML_TYPE_BOOL ErrorCleared;
    XML_TYPE_STR ErrorDescription;
    XML_TYPE_UINT32 ExtClock;
    XML_TYPE_UINT16 Family;
    XML_TYPE_STR InstallDate;
    XML_TYPE_UINT32 L2CacheSize;
    XML_TYPE_UINT32 L2CacheSpeed;
    XML_TYPE_UINT32 L3CacheSize;
    XML_TYPE_UINT32 L3CacheSpeed;
    XML_TYPE_UINT32 LastErrorCode;
    XML_TYPE_UINT16 Level;
    XML_TYPE_UINT16 LoadPercentage;
    XML_TYPE_STR Manufacturer;
    XML_TYPE_UINT32 MaxClockSpeed;
    XML_TYPE_STR Name;
    XML_TYPE_UINT32 NumberOfCores;
    XML_TYPE_UINT32 NumberOfLogicalProcessors;
    XML_TYPE_STR OtherFamilyDescription;
    XML_TYPE_STR PNPDeviceID;
    XML_TYPE_DYN_ARRAY PowerManagementCapabilities;
    XML_TYPE_BOOL PowerManagementSupported;
    XML_TYPE_STR ProcessorId;
    XML_TYPE_UINT16 ProcessorType;
    XML_TYPE_UINT16 Revision;
    XML_TYPE_STR Role;
    XML_TYPE_STR SocketDesignation;
    XML_TYPE_STR Status;
    XML_TYPE_UINT16 StatusInfo;
    XML_TYPE_STR Stepping;
    XML_TYPE_STR SystemCreationClassName;
    XML_TYPE_STR SystemName;
    XML_TYPE_STR UniqueId;
    XML_TYPE_UINT16 UpgradeMethod;
    XML_TYPE_STR Version;
    XML_TYPE_UINT32 VoltageCaps;
};

SER_DECLARE_TYPE(Win32_Processor_Data);

struct _Win32_Processor {
    XmlSerializerInfo *serializerInfo;
    Win32_Processor_Data *data;
    Win32_Processor *next;
};



