/* Generated by hyperv_wmi_generator.py */



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Msvm_ComputerSystem
 */

int
hypervGetMsvmComputerSystemList(hypervPrivate *priv, virBufferPtr query, Msvm_ComputerSystem **list)
{
    return hypervEnumAndPull(priv, query, ROOT_VIRTUALIZATION,
                             Msvm_ComputerSystem_Data_TypeInfo,
                             MSVM_COMPUTERSYSTEM_RESOURCE_URI,
                             MSVM_COMPUTERSYSTEM_CLASSNAME,
                             (hypervObject **)list);
}



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Msvm_ConcreteJob
 */

int
hypervGetMsvmConcreteJobList(hypervPrivate *priv, virBufferPtr query, Msvm_ConcreteJob **list)
{
    return hypervEnumAndPull(priv, query, ROOT_VIRTUALIZATION,
                             Msvm_ConcreteJob_Data_TypeInfo,
                             MSVM_CONCRETEJOB_RESOURCE_URI,
                             MSVM_CONCRETEJOB_CLASSNAME,
                             (hypervObject **)list);
}



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Msvm_MemorySettingData
 */

int
hypervGetMsvmMemorySettingDataList(hypervPrivate *priv, virBufferPtr query, Msvm_MemorySettingData **list)
{
    return hypervEnumAndPull(priv, query, ROOT_VIRTUALIZATION,
                             Msvm_MemorySettingData_Data_TypeInfo,
                             MSVM_MEMORYSETTINGDATA_RESOURCE_URI,
                             MSVM_MEMORYSETTINGDATA_CLASSNAME,
                             (hypervObject **)list);
}



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Msvm_ProcessorSettingData
 */

int
hypervGetMsvmProcessorSettingDataList(hypervPrivate *priv, virBufferPtr query, Msvm_ProcessorSettingData **list)
{
    return hypervEnumAndPull(priv, query, ROOT_VIRTUALIZATION,
                             Msvm_ProcessorSettingData_Data_TypeInfo,
                             MSVM_PROCESSORSETTINGDATA_RESOURCE_URI,
                             MSVM_PROCESSORSETTINGDATA_CLASSNAME,
                             (hypervObject **)list);
}



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Msvm_VirtualSystemSettingData
 */

int
hypervGetMsvmVirtualSystemSettingDataList(hypervPrivate *priv, virBufferPtr query, Msvm_VirtualSystemSettingData **list)
{
    return hypervEnumAndPull(priv, query, ROOT_VIRTUALIZATION,
                             Msvm_VirtualSystemSettingData_Data_TypeInfo,
                             MSVM_VIRTUALSYSTEMSETTINGDATA_RESOURCE_URI,
                             MSVM_VIRTUALSYSTEMSETTINGDATA_CLASSNAME,
                             (hypervObject **)list);
}



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Win32_ComputerSystem
 */

int
hypervGetWin32ComputerSystemList(hypervPrivate *priv, virBufferPtr query, Win32_ComputerSystem **list)
{
    return hypervEnumAndPull(priv, query, ROOT_CIMV2,
                             Win32_ComputerSystem_Data_TypeInfo,
                             WIN32_COMPUTERSYSTEM_RESOURCE_URI,
                             WIN32_COMPUTERSYSTEM_CLASSNAME,
                             (hypervObject **)list);
}



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Win32_Processor
 */

int
hypervGetWin32ProcessorList(hypervPrivate *priv, virBufferPtr query, Win32_Processor **list)
{
    return hypervEnumAndPull(priv, query, ROOT_CIMV2,
                             Win32_Processor_Data_TypeInfo,
                             WIN32_PROCESSOR_RESOURCE_URI,
                             WIN32_PROCESSOR_CLASSNAME,
                             (hypervObject **)list);
}



