/* Automatically generated from ./lxc/lxc_monitor_protocol.x by gendispatch.pl.
 * Do not edit this file.  Any changes you make will be lost.
 */
virNetServerProgramProc virLXCMonitorProcs[] = {
};
size_t virLXCMonitorNProcs = ARRAY_CARDINALITY(virLXCMonitorProcs);
