#include <config.h>
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "virkeepaliveprotocol.h"

bool_t
xdr_keepalive_procedure (XDR *xdrs, keepalive_procedure *objp)
{

         if (!xdr_enum (xdrs, (enum_t *) objp))
                 return FALSE;
        return TRUE;
}
