/* Generated by esx_vi_generator.py */



/* esxVI_LookupComputeResource */
ESX_VI__TEMPLATE__LOOKUP(ComputeResource,
{
    /* ManagedEntity */
    "name\0"

    /* ComputeResource */
    "host\0"
    "resourcePool\0"
},
{
    /* ManagedEntity */
    ESX_VI__TEMPLATE__PROPERTY__CAST_VALUE_FROM_ANY_TYPE(String, name)

    /* ComputeResource */
    ESX_VI__TEMPLATE__PROPERTY__CAST_LIST_FROM_ANY_TYPE(ManagedObjectReference, host)
    ESX_VI__TEMPLATE__PROPERTY__CAST_FROM_ANY_TYPE(ManagedObjectReference, resourcePool)
})



/* esxVI_LookupDatacenter */
ESX_VI__TEMPLATE__LOOKUP(Datacenter,
{
    /* ManagedEntity */
    "name\0"

    /* Datacenter */
    "hostFolder\0"
    "vmFolder\0"
},
{
    /* ManagedEntity */
    ESX_VI__TEMPLATE__PROPERTY__CAST_VALUE_FROM_ANY_TYPE(String, name)

    /* Datacenter */
    ESX_VI__TEMPLATE__PROPERTY__CAST_FROM_ANY_TYPE(ManagedObjectReference, hostFolder)
    ESX_VI__TEMPLATE__PROPERTY__CAST_FROM_ANY_TYPE(ManagedObjectReference, vmFolder)
})



/* esxVI_LookupFolder */
ESX_VI__TEMPLATE__LOOKUP(Folder,
{
    /* ManagedEntity */
    "name\0"

    /* Folder */
    /* no properties */
},
{
    /* ManagedEntity */
    ESX_VI__TEMPLATE__PROPERTY__CAST_VALUE_FROM_ANY_TYPE(String, name)

    /* Folder */
    /* no properties */
})



/* esxVI_LookupHostSystem */
ESX_VI__TEMPLATE__LOOKUP(HostSystem,
{
    /* ManagedEntity */
    "name\0"

    /* HostSystem */
    "configManager\0"
},
{
    /* ManagedEntity */
    ESX_VI__TEMPLATE__PROPERTY__CAST_VALUE_FROM_ANY_TYPE(String, name)

    /* HostSystem */
    ESX_VI__TEMPLATE__PROPERTY__CAST_FROM_ANY_TYPE(HostConfigManager, configManager)
})



/* esxVI_LookupManagedEntity */
ESX_VI__TEMPLATE__LOOKUP(ManagedEntity,
{
    "name\0"
},
{
    ESX_VI__TEMPLATE__PROPERTY__CAST_VALUE_FROM_ANY_TYPE(String, name)
})



